spring.application.name=order-service
server.port=8083

#webclient-url=http://localhost:8080
#frontend-url=http://localhost:3000

webclient-url=http://gateway-service:8080
frontend-url=http://frontend:80

spring.datasource.url=jdbc:postgresql://postgresql:5432/is_order
#spring.datasource.url=jdbc:postgresql://localhost:5432/is_order
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.liquibase.change-log=classpath:liquibase-changelog.xml
spring.liquibase.enabled=true

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=1000MB

#spring.cloud.consul.host=localhost
#spring.cloud.consul.port=8500
#spring.cloud.consul.discovery.enabled=true
#spring.cloud.consul.discovery.register=true
#spring.cloud.consul.discovery.service-name=${spring.application.name}

#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8181}/realms/cloud-realm
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://34.116.235.108/realms/cloud-realm

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always